name: Deploy to AWS EC2

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: development
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd ~/projects/sabpaisa-report-api
            
            # Pull latest changes from development branch
            git fetch origin
            git checkout development
            git pull origin development
            
            # Run deployment script
            chmod +x deploy.sh
            ./deploy.sh
